# Generated by Django 6.0.3 on 2026-04-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grooming", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="type",
        ),
        migrations.AddField(
            model_name="pet",
            name="pet_type",
            field=models.CharField(
                choices=[("dog", "Собака"), ("cat", "Кіт")],
                default="dog",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
