# Generated by Django 6.0.3 on 2026-04-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grooming", "0002_remove_pet_type_pet_pet_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
