# Generated by Django 6.0.3 on 2026-04-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grooming", "0003_appointment_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone_number",
            field=models.CharField(default="0501234567", max_length=10),
            preserve_default=False,
        ),
    ]
