# Generated by Django 6.0.3 on 2026-04-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grooming", "0004_client_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
