# Generated by Django 6.0.3 on 2026-04-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grooming", "0005_alter_client_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
