# Generated by Django 6.0.3 on 2026-04-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grooming", "0006_service_description_service_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestQuickRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                (
                    "pet_type",
                    models.CharField(
                        choices=[("dog", "Собака"), ("cat", "Кіт")], max_length=10
                    ),
                ),
                ("breed", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="groomer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["type"]},
        ),
    ]
